## Making Text Files


all: KOMPLETT.txt

KOMPLETT.txt: $(wildcard [a-z]*.txt)
	echo "## KOMPLETTVERSION SELTERS  --- `date` " > KOMPLETT.txt ;
	echo "## " >> KOMPLETT.txt ;
	echo "## !!! DO NOT EDIT THIS FILE - EDIT SEGMENTS !!!" >> KOMPLETT.txt ;
	echo "## " >> KOMPLETT.txt ;
	echo "## ============================================= " >> KOMPLETT.txt ;
	cat \
	00_wer.txt	\
	01_intro.txt	\
	02_mord.txt	\
	03_palltag.txt	\
	04_k21.txt	\
	05_pato1.txt	\
	06_licht.txt	\
	07_dusche.txt	\
	08_pato2.txt	\
	09_glibber.txt	\
	10_handy.txt	\
	11_spelunk.txt	\
	12_wilma.txt	\
	13_swift.txt	\
	14_show.txt	\
	15_report.txt	\
		>> KOMPLETT.txt

clean:	
	rm -rf KOMPLETT.txt *\~ *\#

.PHONEY: zip

ARCHIVNAME=./Archiv/s-`date +"%Y-%m-%d"`

zip:	clean all
	zip  $(ARCHIVNAME) *.txt;
	chmod ugo-w $(ARCHIVNAME)
