## Making Text Files


all: KOMPLETT.TXT selters_DSFDW.html

KOMPLETT.TXT: $(wildcard *.txt)
	echo "## KOMPLETTVERSION SELTERS  --- `date` " > KOMPLETT.TXT ;
	echo "## " >> KOMPLETT.TXT ;
	echo "## !!! DO NOT EDIT THIS FILE - EDIT SEGMENTS !!!" >> KOMPLETT.TXT ;
	echo "## " >> KOMPLETT.TXT ;
	echo "## ============================================= " >> KOMPLETT.TXT ;
	cat \
	00_wer.txt	\
	01_intro.txt	\
	02_mord.txt	\
	03_palltag.txt	\
	04_k21.txt	\
	05_pato1.txt	\
	06_licht.txt	\
	07_dusche.txt	\
	08_pato2.txt	\
	09_glibber.txt	\
	10_handy.txt	\
	11_spelunk.txt	\
	12_wilma.txt	\
	13_swift.txt	\
	14_show.txt	\
	15_report.txt	\
		>> KOMPLETT.TXT ;

selters_DSFDW.html: $(wildcard *.txt)
	./utils/to_html.py *.txt > $(@)

clean:	
	rm -f KOMPLETT.TXT
	rm -f *\~ *\#
	rm -f selters_DSFDW.html

check:	selters_DSFDW.html
	tidy -e $(<) 2>&1 \
	| grep -v "Warning: .font. attribute .color. has invalid value"

.PHONEY: zip

ARCHIVNAME=./Archiv/s-`date +"%Y-%m-%d"`

zip:	clean all
	zip  $(ARCHIVNAME) *.txt;
	chmod ugo-w $(ARCHIVNAME)
