## Making Text Files


all: KOMPLETT.txt

KOMPLETT.txt: $(wildcard [a-z]*.txt)
	echo "## KOMPLETTVERSION SELTERS  --- `date` " > KOMPLETT.txt ;
	echo "## " >> KOMPLETT.txt ;
	echo "## !!! DO NOT EDIT THIS FILE - EDIT SEGMENTS !!!" >> KOMPLETT.txt ;
	echo "## " >> KOMPLETT.txt ;
	echo "## ============================================= " >> KOMPLETT.txt ;
	cat \
	wer.txt		\
	intro.txt	\
	mord.txt	\
	palltag.txt	\
	k21.txt		\
	pato1.txt	\
	licht.txt	\
	dusche.txt	\
	pato2.txt	\
	glibber.txt	\
	handy.txt	\
	spelunk.txt	\
	wilma.txt	\
	swift.txt	\
	show.txt	\
	report.txt	\
		>> KOMPLETT.txt

clean:	
	rm -rf KOMPLETT.txt *\~ *\#

.PHONEY: zip

ARCHIVNAME=./Archiv/s-`date +"%Y-%m-%d"`

zip:	clean all
	zip  $(ARCHIVNAME) *.txt;
	chmod ugo-w $(ARCHIVNAME)
